[settings]
experimental = false
verbose = false
legacy_version_file = false
legacy_version_file_disable_tools = ["terraform"]

[tools]
go = ["1.25"]
nodejs = ["lts"]
python = ["3.12"]
ruby = ["3.3"]
terraform = ["1.12.2"]
terraform-docs = ["0.18.0"]
java = ["21"]
shellcheck = ["0.10.0"]
kotlin = ["2.0.21"]
gradle = ["8.10.2"]
uv = ["0.8.11"]
